# Site settings
title:          tiaz.dev
description:    "ë°¥ì ì½”. ì ˆì ˆí¬!"
baseurl:        ""
url:            https://tiaz.dev

# Author
author:         
  name:         tiaz
  url:          https://tiaz.dev
  pic:          /assets/img/zo.jpg
  about:        <p class="saying">Eat Sleep Coding.</p>
                <p class="saying">Never Never Giveup.</p>
                <p>ğŸ’« Python &nbsp;|&nbsp; BackEnd &nbsp;|&nbsp; Cloud Architect &nbsp;|&nbsp; DevOps </p>

# Contact links
email: tiaz0128.dev@gmail.com # Add your Email address
phone: # Add your Phone number
website: tiaz.dev # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: tiaz0128 # Add your Github handle
twitter:  # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: tiaz.dev
pinterest: # Add your Pinterest handle

# Build settings
markdown:       kramdown
highlighter:    rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post
  - jekyll-spaceship

# Permalinks
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]


host: "0.0.0.0"
livereload: true
reload_port: 5678